title: Теистическая эволюция
description: Богословско-научные ответы на вопросы о согласовании веры и эволюции.
remote_theme: just-the-docs/just-the-docs
url: ""
exclude:
  - AGENTS.md
plugins:
  - jekyll-include-cache
